knp_snappy:
    pdf:
        enabled:    true
        binary:     '/usr/bin/xvfb-run wkhtmltopdf' # %env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
