sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
sonata_user:
    security_acl: false
    class:                  # Entity Classes
        user:               App\Entity\User
        group:              App\Application\Sonata\UserBundle\Entity\Group

    admin:                  # Admin Classes
        user:
            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

    manager_type: orm
sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
#    security:
#        handler: app.security.handler.role