#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#logout:
#    path: /admin/logout
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin